spring:
  profiles:
    active:
    - develop
    
    
---
spring:
  profiles: develop
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 3000
      
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.qetch.springaop.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  





---
spring:
  profiles: product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 3000

server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.qetch.springaop.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
